# Generated by Django 4.2.23 on 2025-07-02 23:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_postmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.ImageField(blank=True, null=True, upload_to='posts/media/', validators=[api.models.validate_file_size]),
        ),
    ]
